name: RSpec Tests

on:
  push:

jobs:
  test:
    name: Run RSpec Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: gem install bundler && bundle install

      - name: Run RSpec with Github Formatter
        run: rspec --format RSpec::Github::Formatter

